name: Update Visits

on:
  schedule:
    - cron: '*/15 * * * *' # Запуск каждые 15 минут

jobs:
  update-visits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare visit logs
        run: |
          mkdir -p visits
          touch visits/all.log

          # Лог текущего визита
          echo "$(date -u +%s)" >> visits/all.log

      - name: Generate statistics
        id: stats
        run: |
          now=$(date -u +%s)
          today_start=$(date -u -d "$(date -u +%F) 00:00:00" +%s)
          week_start=$(date -u -d "7 days ago" +%s)
          month_start=$(date -u -d "30 days ago" +%s)

          total=$(wc -l < visits/all.log)
          today=$(awk -v start="$today_start" '$1 >= start' visits/all.log | wc -l)
          week=$(awk -v start="$week_start" '$1 >= start' visits/all.log | wc -l)
          month=$(awk -v start="$month_start" '$1 >= start' visits/all.log | wc -l)

          echo "::set-output name=total::$total"
          echo "::set-output name=today::$today"
          echo "::set-output name=week::$week"
          echo "::set-output name=month::$month"

      - name: Update README.md badges
        run: |
          today=${{ steps.stats.outputs.today }}
          week=${{ steps.stats.outputs.week }}
          month=${{ steps.stats.outputs.month }}
          total=${{ steps.stats.outputs.total }}

          sed -i -E "s|!\[Visits Today\]\([^)]+\)|![Visits Today](https://img.shields.io/badge/Today-${today}-blueviolet)|" README.md
          sed -i -E "s|!\[Visits This Week\]\([^)]+\)|![Visits This Week](https://img.shields.io/badge/Week-${week}-blueviolet)|" README.md
          sed -i -E "s|!\[Visits This Month\]\([^)]+\)|![Visits This Month](https://img.shields.io/badge/Month-${month}-blueviolet)|" README.md
          sed -i -E "s|!\[Visits Total\]\([^)]+\)|![Visits Total](https://img.shields.io/badge/Total-${total}-blueviolet)|" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add visits README.md
          git commit -m 'Update visit counters' || echo "No changes to commit"
          git push || echo "No changes to push"
